name: Fetch Data
description: Fetches the latest data
inputs:
  num_provinces:
    description: Number of provinces to fetch
    required: true
    default: 25
  url:
    description: URL to fetch the data
    required: true
    default: 'http://db.ncdd.gov.kh/gazetteer/province/downloadprovince.castle?pv=${province_code}'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.num_provinces }}
    - ${{ inputs.url }}
