name: Create Release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Set up Git
      run: |
        git config --global user.email "dwilkie@gmail.com"
        git config --global user.name "David Wilkie"

    - name: Bump version and publish release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
      run: |
        mkdir -p ~/.gem
        echo -e "---\r\n:rubygems_api_key: $GEM_HOST_API_KEY" > ~/.gem/credentials
        chmod 0600 ~/.gem/credentials
        bundle exec bump minor --tag
        git push
        git push --tags
        bundle exec rake release
