name: Release new gem
on:
  pull_request:
    branches:
      - master

jobs:
  release_gem:
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
