name: release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: ruby
          bump-minor-pre-major: true
          version-file: "lib/pumi/version.rb"

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - uses: ruby/setup-ruby@v1
        if: ${{ steps.release.outputs.release_created }}

      - run: bundle install
        if: ${{ steps.release.outputs.release_created }}

      - name: publish gem
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.GEM_HOST_API_KEY}}"
