name: Bump version
on:
  push:
    branches:
      - release_new_gems
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Setup git
      run: |
        git config --global user.email "dwilkie@gmail.com"
        git config --global user.name "David Wilkie"

    - name: Bump version and push tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        bundle exec bump patch --tag
        git push --tags
